image_meta_path: /Users/paul.williamson/potato_plant_disease/potato-plant-diseases-data/PlantVillage/dataset_metadata.csv
image_data_path: /Users/paul.williamson/potato_plant_disease/potato-plant-diseases-data/PlantVillage/PlantVillage